### ISSUE TITLE
Landing Page - Wireframing

### ISSUE THREAD

**Issue by MatiSalinas** [Esc-IngComp-UNC/computer-laboratory-web-page#1]
Here is the  wireframe for the following components
- header
- carousel
- forms
- About us

let me know if this format is okay.
The "Forms" refer to Supervised Professional Practices (PPS), Integrative Project (PI), or Research forms.

![wireframe1](https://github.com/user-attachments/assets/73b0de9b-7c00-4451-a7b3-d96e5c2b0839)

**Comment by MatiSalinas** [comment]
As for the rest of the components I have some questions...

How many questions are expected to be in the FAQ?
what information will be displayed in the contact component?

**Comment by prietojulii** [comment]
## Language
The language of the page is in Spanish

## FORM:
I would include a single Google Form for contact with interested parties, asking for: first name and last name, email, contact number, CV (optional), and a text box for the reason for contacting. A checklist could also be added to indicate if they are interested in PPS, PI, research, or other

## Contact
**Laboratorio de Computación:**
- Correo: lc.fcefyn@gmail.com
- Instagram: [c.fcefyn](https://www.instagram.com/lc.fcefyn/#)

**FCEFYN:**
- Location:  Av.Velez Sarsfield 1611 Av.Velez Sarsfield 299 , Córdoba, Argentina
- twitter: https://twitter.com/FCEFyN_UNC
- Instagram:https://www.instagram.com/fcefyn_unc/
- youtube: https://www.youtube.com/channel/UCCBcN5DbyBA2C7iZBX4i9nw
- linkedin: https://www.linkedin.com/school/fcefyn

## Projects:
I would add a "Projects" section to showcase some of the laboratory’s projects, including a title, an image, and a brief description.

## FAQ
At the moment, I can think of the following:

- ¿Dónde se encuentra el Laboratorio de Computación?
   El laboratorio está ubicado en el edificio de la Facultad de Ciencias Exactas, Físicas y Naturales, en la Universidad de Córdoba. Arriba del aula  de informática 111.

- ¿Cómo puedo participar en un proyecto de investigación?
Para participar en un proyecto de investigación, primero debes ponerte en contacto con uno de nuestros profesores o investigadores principales. Ellos te proporcionarán información sobre los proyectos en curso y los requisitos necesarios para unirte.

- Que requisitos debo cumplir para unirme a una PPS o PI?
Depende de cada facultad. Para el caso de la FCEFyN se necesita el 70% de las materias aprobadas. Para más información, se puede consultar el siguiente link
[Prácticas FCEFyN](https://fcefyn.unc.edu.ar/facultad/secretarias/academica/escuelas/ingenieria-computacion/practica-supervisada-4/
) [PI FCEFyN](https://fcefyn.unc.edu.ar/facultad/secretarias/academica/escuelas/ingenieria-computacion/proyecto-integrador-7/)

- ¿Cómo puedo sugerir una colaboración o un nuevo proyecto?
Si tienes una idea para una colaboración o un nuevo proyecto, te invitamos a enviarnos una propuesta detallada por correo electrónico. Incluye una descripción del proyecto, tus objetivos y cualquier otro detalle relevante. Nuestro equipo revisará tu propuesta y se pondrá en contacto contigo para discutir posibles pasos a seguir.

**Comment by MatiSalinas** [comment]
Thank you for your feedback.

## Forms
we can embed with an iframe a google form into the page, although we encounter the following problems
- if the form has file upload questions it cannot be embedded.
- limited customization (more research needed to integrate natively). 

![nuevoBoceto1](https://github.com/user-attachments/assets/1f5a033c-c5f7-4e0c-80f4-3465578e31d6)
## Projects
- added two componets as suggested.

![wireframenuevo2](https://github.com/user-attachments/assets/a087a75c-1fbc-4a48-9be0-e3cfcf8417ef)
![wireframenuevo3](https://github.com/user-attachments/assets/0483b601-4740-44fd-98e1-c513a3ac593b)

feel free to make more suggestions.

**Comment by prietojulii** [comment]
Great job!
Sure, Mati, let's omit the CV file upload in the form for now.
Remember to use Spanish for the titles as well. Replace 'FAQ' with 'Preguntas Frecuentes'.

**Comment by MatiSalinas** [comment]
1-Yes, the form can be embedded properly without the file upload feature.
2-Here are the corrections:
![correccion1](https://github.com/user-attachments/assets/0eabcf3f-e7de-483b-bd37-2422ad2d4567)
![correccion2](https://github.com/user-attachments/assets/07a7d263-ef03-4f00-bddf-1f22734f6a2c)


To proceed, we need to establish a color palette.

**Comment by prietojulii** [comment]
Color palette:

https://ar.pinterest.com/pin/454933999876249681/

https://ar.pinterest.com/pin/721490802836808161/

**Comment by GabrielEValenzuela** [comment]
@MatiSalinas 

I have set the estimated completion date (ETA) to September 30th. Please log the number of pomodoros you have completed for this task and let us know if you encounter any blockers or issues that might delay progress.
Your timely updates help us stay on track and address any challenges promptly.

 Thank you!
