### ISSUE TITLE
Landing Page - Front End

### ISSUE THREAD

**Issue by MatiSalinas** [Esc-IngComp-UNC/computer-laboratory-web-page#2]
## Overview
Front End development, I made a fork of the project where I will be implementing  features and making improvements based on the wireframe.
## Fork Information
- **Repository Fork URL:** [https://github.com/MatiSalinas/computer-laboratory-web-page](https://github.com/MatiSalinas/computer-laboratory-web-page)

## Setup Instructions

1. **Clone the Repository**  
   Open your terminal and run the following command:  
   `git clone https://github.com/MatiSalinas/computer-laboratory-web-page.git`
2. **Change the branch**
   `git checkout ramaFrontEnd`
3 **Navigate to the Project Directory**  
   `cd web`

5. **Install Dependencies**  
   Ensure you have [Node.js](https://nodejs.org/) installed, then run:  
   `npm install`

6. **Start the Development Server**  
   `npm run dev`  
   The app will be available at `http://localhost:5173` .
## Additional Notes
- Make sure to use the latest version of Node.js and npm.
- The first commits could not be verified due to an issue with my GPG key, which I resolved in the subsequent ones.
- So far I have made the components for : NavBar, Carousel,AboutUs and News.

---

 
If you have any questions or need further clarification, feel free to point out changes to be made.

**Comment by MatiSalinas** [comment]
# Update on Recent Commits

In the latest commits of my fork, I have made the following improvements:

- Made the **Carousel** and **AboutUs** components responsive, ensuring a better user experience across devices.
- Disabled the animations on the **News** component for mobile view. However, I still need to apply the necessary styles to ensure it looks good on mobile.

**Comment by GabrielEValenzuela** [comment]
# Update

- Review done
